# Constant learning rate scheduler configuration

# Base configuration  
base:
  schedule_name: "constant"
  schedule_args: {}

# Variants
variants:
  default:
    schedule_name: "constant"
    schedule_args: {}

  high:
    schedule_name: "constant"
    schedule_args: {}
