# Configuration pour modèle 3D avec focus sur la troisième composante
# 
# Model: X | theta ~ N(theta, Sigma)
# Prior: theta ~ N(mu0, Sigma0)
#
# Cet exemple montre comment analyser la troisième composante dans un modèle 3D corrélé.

model_type: GaussGaussMultiDimModel
model_class: GaussGaussMultiDimModel

model_args:
  # Prior mean vector (3D)
  mu0: [0.0, 1.0, -0.5]
  
  # Prior covariance with some correlation
  sigma0: [[2.0, 0.5, 0.0],
           [0.5, 3.0, 0.2], 
           [0.0, 0.2, 1.5]]
  
  # Observation noise with different variances per dimension
  sigma: [[0.4, 0.0, 0.0],
          [0.0, 0.6, 0.0],
          [0.0, 0.0, 0.3]]
  
  dim: 3
  
  # Number of observations per sample
  n_obs: 150
  
  # Index of marginal parameter of interest for phi transformation (2 = third component)
  marginal_of_interest: 2

