# 3D Gaussian-Gaussian model with correlations
# More complex multidimensional case with non-diagonal covariances

model_type: GaussGaussMultiDimModel
model_class: GaussGaussMultiDimModel

model_args:
  # Prior mean vector (3D)
  mu0: [0.0, 1.0, -0.5]
  
  # Prior covariance with some correlation
  sigma0: [[2.0, 0.5, 0.0],
           [0.5, 3.0, 0.2], 
           [0.0, 0.2, 1.5]]
  
  # Observation noise with different variances per dimension
  sigma: [[0.4, 0.0, 0.0],
          [0.0, 0.6, 0.0],
          [0.0, 0.0, 0.3]]
  
  dim: 3
  
  # Number of observations per sample
  n_obs: 150
  
  # Index of marginal parameter of interest for phi transformation (0 = first component)
  marginal_of_interest: 0

metadata:
  parameter_space_dim: 3
  analytical_posterior: true
  module: abcnre.simulation.models.gauss_gauss
  version: '1.0'
  description: "3D Gaussian model with correlated prior and heteroscedastic noise"
  use_case: "Complex multidimensional inference, correlation effects"
  scenario: "correlated_3d"
  
  # Mathematical details
  prior_correlation: true
  heteroscedastic_noise: true
  phi_transformation: "theta[0]"  # Extract first component (marginal_of_interest=0)
  
  # Example true parameter vector
  example_true_theta: [0.8, 1.2, -0.3]
  example_phi_true: 0.8  # Expected phi value from example_true_theta[0]
