# Configuration pour modèle 2D avec focus sur la deuxième composante
# 
# Model: X | theta ~ N(theta, Sigma)
# Prior: theta ~ N(mu0, Sigma0)
#
# Cet exemple montre comment analyser la deuxième composante du vecteur de paramètres.

model_type: GaussGaussMultiDimModel
model_class: GaussGaussMultiDimModel

model_args:
  # Prior mean vector (2D example)
  mu0: [0.0, 0.0]
  
  # Prior covariance matrix (2x2)
  sigma0: [[4.0, 0.0], 
           [0.0, 4.0]]
  
  # Observation noise covariance matrix (2x2)  
  sigma: [[0.25, 0.0],
          [0.0, 0.25]]
  
  # Dimension is inferred from mu0
  dim: 2
  
  # Number of observations per sample
  n_obs: 10
  
  # Index of marginal parameter of interest for phi transformation (1 = second component)
  marginal_of_interest: 1

metadata:
  parameter_space_dim: 2
  analytical_posterior: true
  module: abcnre.simulation.models.gauss_gauss
  version: '1.0'
  description: "2D Gaussian location model focusing on second parameter component"
  use_case: "Marginal inference for second component"
  focus_parameter: "theta_1 (second component)"
  
  # Mathematical details
  conjugate_prior: true
  sufficient_statistic: "sample_mean_vector"
  phi_transformation: "theta[1]"  # Extract second component
  
  # Example true parameter vector for simulation studies
  example_true_theta: [1.5, -0.8]
  example_phi_true: -0.8  # Expected phi value from example_true_theta[1]
