# Configuration template for Multidimensional Gaussian-Gaussian Model
#
# Model: X | theta ~ N(theta, Sigma)  
# Prior: theta ~ N(mu0, Sigma0)
#
# Multidimensional extension where theta is a vector parameter.

model_type: GaussGaussMultiDimModel
model_class: GaussGaussMultiDimModel

model_args:
  # Prior mean vector (2D example)
  mu0: 0
  
  # Prior covariance matrix (2x2)
  sigma0: 10.0
  
  # Observation noise covariance matrix (2x2)  
  sigma: 1.0
  
  # Dimension is inferred from mu0
  dim: 2
  
  # Number of observations per sample
  n_obs: 10
  
  # Index of marginal parameter of interest for phi transformation (0 = first component)
  marginal_of_interest: 0
