# Configuration template for 1D Gaussian-Gaussian Model
# 
# Model: X | theta ~ N(theta, sigma^2)
# Prior: theta ~ N(mu0, sigma0^2)
#
# This is a standard conjugate prior setup where the posterior
# has a closed-form analytical solution.

model_type: GaussGaussMultiDimModel
model_class: GaussGaussMultiDimModel
model_args:
  mu0: 0.0        # Prior mean for theta
  sigma0: 10.0     # Prior standard deviation for theta
  sigma: 1.0      # Known observation noise standard deviation
  n_obs : 10  # Number of observations per sample
  dim : 1
  marginal_of_interest: 0  # Index of the marginal parameter of interest for phi transformation (0 = first component)
