# Configuration for DeepSet-based summary statistics learning
# Unified config format matching inference module patterns  
# Used when sample_is_iid = True (independent, identically distributed data)

# Network selection (automatic based on sample_is_iid)
type: "DeepSet"   
verbose: true    
       # Network type
# Network architecture
network_config:
  # DeepSet architecture
  phi_hidden_dims: [32, 16]   # Hidden dimensions for φ function (per-element processing)
  rho_hidden_dims: [32, 16]   # Hidden dimensions for ρ function (post-pooling)
  pooling_type: "mean"        # Pooling type: 'mean', 'sum', 'max', 'attention'
  summary_dim: 1              # Output parameter dimension
  use_layer_norm: true        # Layer normalization
  dropout_rate: 0.0           # Dropout rate
  activation: "relu"          # Activation function

training_config:
  learning_rate: 0.0003       # Learning rate
  num_epochs: 10           # Number of training epochs
  batch_size: 256             # Batch size for training
  n_batch: 40                 # Number of batches per epoch

  optimizer: "adam"           # Optimizer type
  weight_decay: 0.0          # Weight decay

  lr_scheduler: "constant"    # 'constant', 'cosine', 'exponential', 'reduce_on_plateau'
  lr_scheduler_args: {}       # Additional scheduler arguments
           # Verbose output
  n_sim_max: null            # Maximum simulations (null = unlimited)

