network_config:
  network_type: MLPNetwork
  network_args:
    hidden_dims:
    - 128
    - 64
    - 32
    output_dim: 1
    activation: relu
    dropout_rate: 0.0
    use_batch_norm: false
    final_activation: null
  input_dims:
    phi_dim: 1
    summary_stat_dim: 1
training_config:
  learning_rate: 0.001
  n_samples_per_epoch: 10240
  batch_size: 256
  num_epochs: 50
  validation_split: 0.2
  early_stopping_patience: 10
  optimizer: adam
  weight_decay: 0.0
  lr_scheduler:
    schedule_name: reduce_on_plateau
    schedule_args:
      patience: 10
      factor: 0.5
  store_thetas: true
  num_thetas_to_store: 10000
metrics:
  final_val_loss: 0.4008302688598633
  final_val_accuracy: 0.818359375
  epochs_trained: 30
  total_sim_count: 2967947
paths:
  weights_path: /Users/antoineluciano/Documents/Recherche/ABC-SBI-1/abcnre/examples/notebooks/gauss_example/gauss_1D_weights.npy
  phis_path: /Users/antoineluciano/Documents/Recherche/ABC-SBI-1/abcnre/examples/notebooks/gauss_example/gauss_1D_phis.npy
