# Regressor configuration for summary statistics learning
# Used with: abcnre create_simulator --learn-stats --regressor-config this_file.yaml

network_name: "deepset"
network_size: "default"
training_size: "default"
lr_scheduler_name: "cosine"
experiment_name: "summary_learner_deepset"

# Training overrides
overrides:
  training:
      num_epochs: 200
      batch_size: 1024
      learning_rate: 0.001
      weight_decay: 0.001
      optimizer: "adamw"
  network:
    network_args: 
      activation: "elu"
