network_name: "deepset"
network_size: "default"
training_size: "default"
lr_scheduler_name: "constant"
lr_scheduler_variant: "default"
stopping_rules_variant: "balanced"
experiment_name: "summary_stats_deepset_training"

# Optional overrides for specific training parameters
overrides:
  training:
      num_epochs: 200
      batch_size: 1024
      learning_rate: 0.001
      weight_decay: 0.001
      optimizer: "adamw"
  network:
    network_args: 
      activation: "elu"
