network_name: "conditioned_deepset"
network_size: "default"
training_size: "default"
lr_scheduler_name: "reduce_on_plateau"
lr_scheduler_variant: "default"
stopping_rules_variant: "balanced"
experiment_name: "nre_conditioned_deepset_training"

# Optional overrides for specific training parameters
overrides:
  num_epochs: 200
  batch_size: 1024
  learning_rate: 0.01
  weight_decay: 1e-3
  optimizer: "adamw"
