# Fast classifier configuration for quick testing
# Used with: abcnre create_estimator --classifier-config this_file.yaml

network_name: "mlp"
network_size: "default"
training_size: "default"
lr_scheduler_name: "reduce_on_plateau"
experiment_name: "classifier_mlp_fast"

# Training overrides for fast testing
overrides:
  num_epochs: 50
  batch_size: 512
  learning_rate: 0.01
  optimizer: "adam"
  weight_decay: 0.0
